spring:
  application:
    name: dayone-financial

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dayone;DB_CLOSE_DELAY=-1
    username: sa
    password: ''

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      show-sql: true
      defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

